hackforla/ballotnav

backend/db/schema.sql
moving this from sheets simply because of syntax highlighting and visibility (sheets gets so cluttered so fast!)
=> add example schema

client/web/src/components/SearchResult.css, client/web/src/components/SearchResult.js, client/web/src/global.css, client/web/src/pages/Home.css, client/web/src/pages/Home.js
Improved general layout and CSS styling. There is some unfinished elements (search input and the bottom search result is cut off). Pushing so repo is up to date.
=> general layout improvements

scrapers/Michigan.py
Scraping script for Michigan, that pulls the html data for all counties.Does not include formatting of data.
=> scraper:Michigan

.github/ISSUE_TEMPLATE/blank-issufeature-suggestione.md, .github/ISSUE_TEMPLATE/feature-suggestion.md
=> Update issue templates

.github/workflows/backend-build.yaml
testing ci on backend build; still needs github secrets added from 1pass
#29
=> Add CI for backend build

.github/CODEOWNERS, README.md
Added protection to master branch
=> Technologies + Code Owners

.github/workflows/backend-build.yaml, backend/Dockerfile, backend/config/config.json, backend/docker-compose.yml, backend/entrypoint.sh, backend/migrations/20200919061608-create-state.js, backend/models/state.js
adds initial tables we'll need and shows an example of how to do this
=> add initial tables

backend/db/create-postgis-extension.sql
#101 
not sure if this is all we need but i expect it's enough to start; 
i've applied this to the dev db and will use the same to setup prod db when the time comes :tada:
=> #101 add script for postgis setup on cloud db

backend/Makefile, backend/README.md
=> some docs is better than no docs

backend/.sequelizerc, backend/app.js, backend/config/config.js, backend/config/config.json, backend/controllers/jurisdictions.js, backend/controllers/locations.js, backend/controllers/states.js, backend/middleware/auth.js, backend/models/index.js, backend/package.json
we allow passing secrets via environment vars 
so we dont have to code it into the json file. yay!
=> update db config options for deployment;

backend/controllers/user.js, backend/log.js, backend/package-lock.json, backend/package.json
setup winston and logging on user routes
=> setup backend logging

.gitignore, backend/_misc/requests/Makefile, backend/_misc/requests/README.md, backend/_misc/requests/headers.txt, backend/_misc/requests/login.sh, backend/_misc/requests/update-jurisdiction.json, backend/_misc/requests/update.sh, backend/_misc/requests/wip-jurisdiction.json, backend/_misc/requests/wip-location.json, backend/controllers/error.js, backend/controllers/jurisdictions.js, backend/controllers/user.js, backend/middleware/auth.js, backend/routes/jurisdictions.js
adds endpoints for `WipJurisdiction` data, and some scripts etc for devving. 
i think that can be pulled out no problem still
=> Wip jurisdiction endpoint

backend/Dockerfile, backend/Makefile, backend/README.md, backend/controllers/jurisdictions.js, backend/docker-compose.yml, backend/routes/jurisdictions.js
=> add some docker helpers for really super clean rebuild

backend/_misc/requests/ballotnav-local.postman_collection.json, backend/controllers/jurisdictions.js, backend/controllers/locations.js, backend/package-lock.json, backend/package.json, backend/routes/jurisdictions.js, backend/routes/locations.js, backend/routes/schemas.js
=> Wip location endpoints

backend/controllers/user.js, backend/routes/schemas.js, backend/routes/user.js
endpoint for adding a jurisdiction assignment to a volunteer;
```json
{
"userId": 1,
"jurisdictionIds": [2,3]
"status": "editor"
}
```
```json
{
"status": "ok",
"results": [
{
"id": 4,
"jurisdictionId": 2,
"userId": 1,
"status": "editor",
"createdAt": "2020-09-30T07:03:30.114Z",
"updatedAt": "2020-09-30T07:03:30.114Z",
},
{
"id": 5,
"jurisdictionId": 3,
"userId": 1,
"status": "editor",
"createdAt": "2020-09-30T07:03:30.114Z",
"updatedAt": "2020-09-30T07:03:30.114Z",
}
]
}
```
=> API: adds create assignment route

.github/workflows/client.yaml, .github/workflows/web-admin.yaml, .gitignore, client/web-admin/src/components/Main.js
this adds a job for deploying the **dev environment** admin webui to `admin.dev.ballotnav.org` on merge to the main branch. 
deploy to production will run through a different flow triggered by github release.
=> adds cicd for web-admin

.github/workflows/backend-build.yaml, .github/workflows/web-admin.yaml, client/web-admin/src/components/Dashboard/EditTable.js
on merge to master we build and deploy the backend to dev evironment https://api.dev.ballotnav.org
=> cicd: add continuous deploy for dev environment backend

.github/workflows/web-admin.yaml
=> cicd: fix the conditional branch check

client/web/src/components/map/Map.jsx, client/web/src/styles/map/_map.scss
Referenced in https://github.com/hackforla/ballotnav/issues/111
Added alert to map component
=> add alert to map component mobile responsive

backend/migrations/20201013224400.js, backend/migrations/sql/20201013224400-up.sql, backend/models/user.js
- Per conversation with Adam, Randall, etc., tonight, added two fields to user model
- Corrects logic problem in wip_jurisdiction publish process
=> Database improvements

backend/controllers/admin.js, client/web-admin/src/components/Dashboard/AssignJurisdictions/index.js, client/web-admin/src/components/Dashboard/EditJurisdiction/EditTable/Row.js, client/web-admin/src/components/Dashboard/EditJurisdiction/EditTable/index.js, client/web-admin/src/components/Dashboard/EditJurisdiction/HeaderButtons.js, client/web-admin/src/components/Dashboard/EditJurisdiction/LocationForm.js, client/web-admin/src/components/Dashboard/EditJurisdiction/index.js, client/web-admin/src/components/Dashboard/EditState/index.js, client/web-admin/src/components/Dashboard/Layout/Header.js, client/web-admin/src/components/Dashboard/Layout/index.js, client/web-admin/src/components/Dashboard/ListJurisdictions/index.js, client/web-admin/src/components/Dashboard/ListStates/index.js, client/web-admin/src/components/Dashboard/Review/index.js, client/web-admin/src/components/core/AutoForm.js, client/web-admin/src/models/index.js, client/web-admin/src/models/jurisdiction.js, client/web-admin/src/services/api/jurisdictions.js
- update endpoint working and integrated (except for some minor date-formatting issues)
- better layout
=> Admin client/getting closer to something usable

backend/README.md
=> adds raw data download link to readme

.github/workflows/backend-build.yaml, backend/.dockerignore, backend/Dockerfile, backend/app.js, backend/package-lock.json, backend/package.json, backend/routes/index.js
trigger a production deploy from github release
note: this assumes that we release out of master. if we create the github release targeting a different branch it isn't guaranteed to work!
=> add deploy step for production environment

.github/workflows/web-admin.yaml
similar to the backend build we deploy to prod on publishing
a github release.
=> adds cicd for admin ui to prod environment

backend/controllers/admin.js, client/web-admin/src/components/Dashboard/Layout/DrawerMenu.js
hi @adamkendis, the list jurisdictions endpoint was returning almost 12MB of data on the dev site, so I trimmed it to just the fields that the assignments view needs. Also, removed the Edit States option from the admin menu since it's not working yet.
=> Admin client/small fixes

backend/migrations/20201019105000.js, backend/migrations/sql/20201019105000-up.sql
- Adds permanent-geolocation processing table
- Adds view for "measurements" (of statistics regarding jurisdiction completion/etc)
=> DB improvements

.github/workflows/web-admin.yaml
Github expression syntax for boil does not do what the docs say
=> Fix condition for deploy

.github/workflows/web-admin.yaml
=> cicd fix typo

backend/migrations/20201019131500.js, backend/migrations/sql/20201019131500-up.sql
- Ensures that published wip_jurisdictions can no longer be updated or deleted
- On public.location, ensures that geom_point always equals latitude+longitude whenever possible
=> DB improvement

backend/controllers/public.js, backend/routes/public.js
adding routes for listing states, listing jurisdictions with a state, and getting a jurisdiction
=> added public routes

backend/controllers/public.js, backend/routes/public.js
get state by stateid
```javascript
axios.get('/states/12').then(data => {
console.log(data)
})
```
=> backend: adds a get state by id

client/web/src/components/main/Footer.jsx, client/web/src/styles/_bulma.scss, client/web/src/styles/main/_footer.scss
Added desktop responsiveness to footer ui
=> Footer - desktop responsivess

.github/workflows/client-deployment.yaml, .github/workflows/client-integration.yaml, client/web/package.json, client/web/src/Routes.jsx, client/web/src/components/info/CountyInfo.jsx, client/web/src/components/info/ResultCard.jsx, client/web/src/components/info/ResultDetail.jsx, client/web/src/components/info/ResultList.jsx, client/web/src/components/main/About.jsx, client/web/src/components/main/Home.jsx, client/web/src/components/main/Press.jsx, client/web/src/components/main/Volunteer.jsx, client/web/src/components/map/Map.jsx, client/web/src/components/map/MapContainer.jsx
Our current client workflow runs _after_ the code has been reviewed, and has frequently failed due to build errors. The source of these errors are React console "warnings" that turn into fatal errors during the build step.
This new workflow runs _before_ the code is reviewed, and ensures that the it is possible to build the client. It also checks whether the code has been linted. If either test fails, the PR doesn't make it to review.
Practically speaking, this means that devs will have to (1) fix console warnings, and (2) lint their code by running `npm run lint`, before submitting PRs to master.
(This only applies to the public-facing client, not the backend or admin client).
=> new workflow to lint and build client before code reviews

backend/controllers/public.js, backend/routes/public.js
A new endpoint to support the state/jurisdiction dropdowns. Lists the states in alphabetical order, and for each state, the jurisdictions in alphabetical order.
=> added endpoint for dropdowns

client/web/src/components/main/Footer.jsx, client/web/src/components/main/Header.jsx, client/web/src/styles/main/_footer.scss, client/web/src/styles/main/_header.scss, client/web/src/styles/main/_volunteer.scss
-added hamburger menu
-responsive navbar changes
-small edit to Volunteer cards where copy was getting cut off at small mobile sizes
=> Hamburger menu, navbar

client/web/README.md, client/web/src/components/info/ResultDetail.jsx, client/web/src/components/main/Header.jsx, client/web/src/styles/info/_result-detail.scss, client/web/src/styles/main/_footer.scss
This commit adds a couple small style improvements to the app, including ensuring that the facebook and twitter share icons always appear, sending the footer to the back of the page's z-axis, and styling hour information in the ResultDetail to improve readability.
=> Small style improvements

client/web/src/components/SearchBar/Geocoder.js, client/web/src/components/info/ResultList.jsx
=> some small tweaks

backend/infrastructure/lb.tf, backend/infrastructure/main.tf, backend/infrastructure/templates/task-definition.json, backend/infrastructure/variables.tf
Adds some minor config changes to lower hosting costs by sharing resources. 
- prepend a `{stage}_` prefix to avoid name collisons
- apply formatting for :sunglasses: nice looks
=> Merge backend infra

client/web/src/components/MapPage/shared/LocationDetail/DirectionsButton.js, client/web/src/components/MapPage/shared/LocationDetail/index.js
- include directions button even if we don't have the user's location (they can add it on google maps)
- use address strings instead of lnglats in google maps link
=> improved directions button

client/web/package-lock.json, client/web/package.json, client/web/src/App.jsx, client/web/src/components/main/Header.jsx, client/web/src/styles/main/_header.scss
- fixes an issue in mobile safari where the browser bottom bar goes over the app
=> safari mobile fix

client/web/src/components/main/Home/Desktop.js, client/web/src/components/main/Home/Mobile.js
Added a notice above the search bar that BallotNav is displaying drop-off results from Georgia
=> Notice on home page that results are restricted to Georgia

.github/workflows/client-deployment.yaml, client/web/src/services/api.js, client/web/src/services/mapbox.js
hey @jafow, could you add a github secret called MAPBOX_TOKEN with the token from 1password? I don't have the creds to do that. thanks!
=> add mapbox token to env / update deployment workflow

client/web/src/components/main/About.jsx, client/web/src/components/main/Header.jsx, client/web/src/components/main/Home/Desktop.js, client/web/src/components/main/Home/Mobile.js, client/web/src/components/main/Volunteer.jsx, client/web/src/styles/main/_about.scss, client/web/src/styles/main/_volunteer.scss
- About page copy is updated to remove "November election" and add Code for Atlanta to participating brigades
- Press link is removed for now
- "Jan. 5, 2021"
- Styling and copy updates to the Volunteer page
=> 263: Updated About and Volunteer pages

client/web/src/components/MapPage/shared/LocationDetail/VerifyBox.js, client/web/src/components/MapPage/shared/LocationDetail/index.js, client/web/src/components/MapPage/shared/VerifyAlert.js, client/web/src/components/main/Volunteer.jsx
tiny stuff, mostly this is to trigger the deploy workflow
=> Client/more UI

backend/controllers/public.js, backend/models/jurisdictionphone.js, backend/models/statephone.js, backend/models/stateurl.js
adds phone and url type names to api responses so we can use them in the UI
=> added phoneNumberType, urlType to getState and getJurisdiction responses

client/web/src/Routes.jsx, client/web/src/components/main/Footer.jsx, client/web/src/components/main/PrivacyPolicy.jsx, client/web/src/styles/main/_privacy-policy.scss, client/web/src/styles/styles.scss
The privacy policy is added as a page of the site
=> Privacy policy added as HTML

client/web/src/components/MapPage/shared/LocationCard/LocationSchedule/index.js
just a quick fix for a layout issue
=> fixed LocationSchedule layout

.github/workflows/web-admin.yaml
combine the dev & prd workflow into 1.
Since we must rebuild the client for a production deploy just use the same workflow and branch based on whether it's a `release` or push to `master`.
=> Ci adminprd

client/web/src/components/MapPage/shared/LocationDetail/CheckSteps/index.js, client/web/src/components/main/About.jsx, client/web/src/components/main/Volunteer.jsx, client/web/src/styles/main/_privacy-policy.scss, client/web/src/styles/main/_volunteer.scss
- About and Volunteer pages are updated with new copy
- Deadline info is added for requesting an absentee ballot under "Check Your Steps"
- Styling tweaks in Privacy Policy page
=> Updated About and Volunteer pages, added deadline info for requesting absentee ballot

.github/workflows/web-admin.yaml
fixes copy pasta syntax error in web-admin CI action.
=> ci: fix syntax error in web-admin release flow

README.md, client/web/src/styles/main/_header.scss
Changed menu to 100 viewport width and removed border radius from menu for a cleaner look on mobile.
=> Mobilefixes

scrapers/scrape_Illinois_locations_html.ipynb, scrapers/scrape_Michigan_locations_html.ipynb
=> Upload scrapers
